Repository City-of-Helsinki/helerm-ui, pull requests merged in 2018-09, with the labels that each got.

#232 Use FEEDBACK_URL instead of hardcoded mailto-link
  .env.example
  .eslintrc
  config/index.js
  src/components/Banner/index.js
Labels: in progress

#233 piwik configuration with piwik-react-router package
  .env.example
  config/index.js
  package.json
  src/main.js
  yarn.lock
Labels: in progress

#235 Fix add phase add action information system bug
  .gitignore
  src/components/Tos/AddElementInput/AddElementInput.js
Labels: in progress

#234 Update & cleanup travis config a bit
  .travis.yml
Labels: in progress

#239 Filtered search and export
  .nvmrc
  config/constants.js
  package.json
  src/components/Exporter/Exporter.js
  src/components/Exporter/index.js
  src/components/InfinityMenu/EmptyTree.js
  src/components/InfinityMenu/infinityMenu.js
  src/components/Navigation/Navigation.js
  src/components/Navigation/Navigation.scss
  src/components/Navigation/SearchFilter.js
  src/components/Navigation/reducer.js
  yarn.lock
Labels: enhancement, in progress

#240 Make build work without Git-context
  config/index.js
Labels: bug, in progress

#242 Add route for filtered search
  config/constants.js
  src/components/Exporter/Exporter.js
  src/components/InfinityMenu/infinityMenu.js
  src/components/Navigation/Navigation.js
  src/components/Navigation/NavigationContainer.js
  src/components/Navigation/SearchFilter.js
  src/routes.js
  yarn.lock
Labels: in progress
